version: '2'
services:
    mysql5.7:
        image: mysql:5.7
        container_name: mysql_5.7
        ports:
            - 3307:3306
        volumes:
            - ./init:/docker-entrypoint-initdb.d
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: secret

    mysql8.0:
        image: mysql:8.0
        container_name: mysql_8.0
        ports:
            - 3308:3306
        volumes:
            - ./init:/docker-entrypoint-initdb.d
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: secret