postgresql:
    image: postgres:12.2
    container_name: postgres12.2
    ports:
        - 5433:5432
    volumes:
        - ./init:/docker-entrypoint-initdb.d
    environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: secret
        POSTGRES_DB: demo
        POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres12.2
    restart: always
    user: root