version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "8080:8080"
    depends_on:
      - php
    volumes:
      - ./:/src
  mariadb:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sample
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
  php:
    build:
      dockerfile: ./docker/php/Dockerfile
      context: .
    ports:
      - "9912:9912"
    working_dir: /src
    environment:
      COMPOSER_MEMORY_LIMIT: '-1'
    volumes:
      - ./:/src:cached
  phpmyadmin:
      platform: linux/amd64
      image: phpmyadmin/phpmyadmin
      depends_on:
        - mariadb
      ports:
        - "3000:80"
      environment:
        PMA_HOST: mariadb
        PMA_USER: root
        PMA_PASSWORD: password
