version: '2'
services:
    mysql8.0:
        image: mysql:8.0
        container_name: mysql_8.0
        ports:
            - 3380:3306
        volumes:
            - ./init:/docker-entrypoint-initdb.d
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: secret
